### ISSUE TITLE
Add ability to ignore a build while keeping it in the dashboard

### ISSUE THREAD

**Issue by DavidRogers** [DavidRogers/kato#4] opened 2014-08-29 03:00 UTC
This is mainly to make certain builds not show up in the status notifications, especially the tray icon.

**Comment by sharwell** [comment] 2016-09-13 13:40
This is related to (but not a duplicate of) #21. I would find both helpful.

**Comment by DavidRogers** [comment] 2017-08-01 22:40
This shouldn't be necessary now since #21 has been addressed in https://github.com/DavidRogers/kato/commit/ed0fc08f4c42ef51d2d3d57244e264b5680b0a45.

**Closed** 2017-08-01 22:41 UTC
Labels: enhancement, wontfix
